---
# Configure secure default virtual host and enable support for SSL connections

- name: configure default SSL nginx virtual host
  template: src=etc/nginx/sites-available/default-ssl.j2 dest=/etc/nginx/sites-available/default-ssl.conf

- name: enable default SSL nginx virtual host
  file: src=/etc/nginx/sites-available/default-ssl.conf dest=/etc/nginx/sites-enabled/default-ssl.conf state=link
  notify:
    - Restart Nginx
