---
# Configure secure default virtual host and enable support for SSL connections

- name: configure default SSL nginx virtual host
  template: src=etc/nginx/sites-available/default-ssl.j2 dest=/etc/nginx/sites-available/default-ssl.conf

- name: enable default SSL nginx virtual host
  file: src=/etc/nginx/sites-available/default-ssl.conf dest=/etc/nginx/sites-enabled/default-ssl.conf state=link
  notify:
    - Restart Nginx

- name: create directory for nginx SSL configuration
  file: path=/etc/nginx/ssl state=directory

- name: copy SSL rules to nginx configuration directory
  copy: src=etc/nginx/ssl/ssl.rules dest=/etc/nginx/ssl

- name: copy SSL DH parameter key to nginx configuration directory
  copy: src=etc/nginx/ssl/dhparam2048.pem dest=/etc/nginx/ssl
