---
# Installs and configures Nginx web server

- include: install-nginx.yml

- include: configure-ssl.yml
  when: nginx_default_var_www_ssl_enabled == true

- include: configure-document-root.yml

- include: app-user.yml

- include: configure-default-http-virtualhost.yml

- include: configure-default-https-virtualhost.yml
  when: nginx_default_var_www_ssl_enabled == true
